version: '3.9'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs14-chated
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app
      - /app/node_modules
  
  db:
    container_name: db
    image: postgres:14
    restart: always
    environment: 
      POSTGRES_USER: aruuke
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chated
    ports: 
      - 5433:5433
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: {}
